pip install cv2
pip install argparse
pip install imutils
pip install time
pip install os
pip install json
pip install enum
pip install mmdet
pip install ctypes
pip install pillow
pip install sklearn
pip install matplotlib
pip install plotly
pip install numba
pip install numpy
pip install filterpy
pip install scipy
pip install collections
pip install werkzeug
pip install youtube_dl
pip install glob
pip install flask
pip install re
pip install copy
pip install itertools
pip install pandas
pip install math
pip install bezier